// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalAddonTestAddDao is internal type for wrapping internal DAO implements.
type internalAddonTestAddDao = *internal.AddonTestAddDao

// addonTestAddDao is the data access object for table hg_addon_TestAdd.
// You can define custom methods on it to extend its functionality as you wish.
type addonTestAddDao struct {
	internalAddonTestAddDao
}

var (
	// AddonTestAdd is globally public accessible object for table hg_addon_TestAdd operations.
	AddonTestAdd = addonTestAddDao{
		internal.NewAddonTestAddDao(),
	}
)

// Fill with you ideas below.
