// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalAddonClientUpdateDao is internal type for wrapping internal DAO implements.
type internalAddonClientUpdateDao = *internal.AddonClientUpdateDao

// addonClientUpdateDao is the data access object for table hg_addon_client_update.
// You can define custom methods on it to extend its functionality as you wish.
type addonClientUpdateDao struct {
	internalAddonClientUpdateDao
}

var (
	// AddonClientUpdate is globally public accessible object for table hg_addon_client_update operations.
	AddonClientUpdate = addonClientUpdateDao{
		internal.NewAddonClientUpdateDao(),
	}
)

// Fill with you ideas below.
