// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalAdminUserAtchDao is internal type for wrapping internal DAO implements.
type internalAdminUserAtchDao = *internal.AdminUserAtchDao

// adminUserAtchDao is the data access object for table hg_admin_user_atch.
// You can define custom methods on it to extend its functionality as you wish.
type adminUserAtchDao struct {
	internalAdminUserAtchDao
}

var (
	// AdminUserAtch is globally public accessible object for table hg_admin_user_atch operations.
	AdminUserAtch = adminUserAtchDao{
		internal.NewAdminUserAtchDao(),
	}
)

// Fill with you ideas below.
