// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalClientUpdateDao is internal type for wrapping internal DAO implements.
type internalClientUpdateDao = *internal.ClientUpdateDao

// clientUpdateDao is the data access object for table hg_client_update.
// You can define custom methods on it to extend its functionality as you wish.
type clientUpdateDao struct {
	internalClientUpdateDao
}

var (
	// ClientUpdate is globally public accessible object for table hg_client_update operations.
	ClientUpdate = clientUpdateDao{
		internal.NewClientUpdateDao(),
	}
)

// Fill with you ideas below.
